### ISSUE TITLE
Roadmap to begin

### ISSUE THREAD

**Issue by MireilleBF** [MireilleBF/JustificationDiagram#9]
- [x] 1. Prendre connaissance de l'environnement de travail en clonant cet espace
- [x] 2. Premier diagramme de justification : 
      a. Décrire dans un diagramme de justification très simple, le résumé de  l'intégration continue (dans _actions_), actuellement définie : build & test puis production d'un rapport jacoco etc.. 
       b. générer la vue png 
       c. générer la liste de todo
- [x] 3. Proposer une modélisation très simple résumant une étape intégration 
      a. enregistrement des évidences(supports) (voir #1 )
      b. construction d'un diagramme de justification "instance" montrant les étapes qui ont bien été réalisées
      c. visualiser ce diagramme sous la forme d'un png
      d. imaginez une intégration automatique dans le site pour visualiser l'état de justification du projet
- [x] 4. Bien évidemment, mettez à jour le mode d'emploi de votre logiciel (cf. #3)
- [x] 5. A vous, des pistes ont déjà été exprimées sous la forme d'issues, ici en voici d'autres moins élaborées
       -   Proposer une visualisation pour les diagrammes de justification instance dont certains todo n'ont pas été réalisés
       -   Ajouter des outils d'IC (e.g. #5 )
       -   Vérifier le contenu des évidences
       -    Ajouter des vérification dans les stratégies de justification
